In [9]:
from scipy import stats
import numpy as np

In [19]:
stats.norm.ppf(0.999)

3.090232306167813

In [14]:
?stats.norm.ppf

Signature: stats.norm.ppf(q, *args, **kwds)
Docstring:
Percent point function (inverse of `cdf`) at q of the given RV.

Parameters
----------
q : array_like
    lower tail probability
arg1, arg2, arg3,... : array_like
    The shape parameter(s) for the distribution (see docstring of the
    instance object for more information)
loc : array_like, optional
    location parameter (default=0)
scale : array_like, optional
    scale parameter (default=1)

Returns
-------
x : array_like
    quantile corresponding to the lower tail probability q.
File:      ~/anaconda3/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py
Type:      method

In [12]:
np.random.choice(1000,(2,23,4))

array([[[954, 959, 928, 812],
        [896, 486, 280, 428],
        [162, 370, 749, 218],
        [ 57, 659, 270, 660],
        [232, 636, 356,  98],
        [232, 305,  89, 424],
        [305, 274, 481, 944],
        [137, 137, 287, 393],
        [899, 232, 867, 338],
        [ 81, 466, 767, 341],
        [882, 679, 474, 440],
        [123, 539, 983, 964],
        [ 54, 920, 427, 841],
        [188, 699, 334, 329],
        [466, 385, 830,  91],
        [ 12, 574, 463, 116],
        [333, 825, 666, 216],
        [900, 292, 281, 376],
        [ 19, 581, 841, 575],
        [ 54, 711, 784, 208],
        [483, 354,  60, 510],
        [124, 197, 367, 933],
        [796, 821, 145,  79]],

       [[757, 301, 275, 368],
        [137, 110, 468, 208],
        [707, 152, 171, 355],
        [115, 344, 648, 446],
        [146, 673, 938, 316],
        [261, 760, 556, 528],
        [230, 186, 490, 315],
        [155, 640, 387, 258],
        [234, 147, 866, 681],
        [552,   5, 972, 366],
        

In [10]:
?np.random.choice

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the ``choice`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a uniform distribution over all
    entr

In [7]:
stats.poisson.rvs(mu=5, loc=5, size=10)

array([ 7, 10,  8, 12, 13,  8, 10, 13,  9, 11])

In [8]:
stats.poisson.rvs(mu=5, loc=500, size=10)

array([506, 506, 505, 504, 508, 504, 512, 506, 502, 503])

In [4]:
?stats.poisson

Signature:       stats.poisson(*args, **kwds)
Type:            poisson_gen
String form:     <scipy.stats._discrete_distns.poisson_gen object at 0x7ff07ee2dc70>
File:            ~/anaconda3/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py
Docstring:      
A Poisson discrete random variable.

As an instance of the `rv_discrete` class, `poisson` object inherits from it
a collection of generic methods (see below for the full list),
and completes them with details specific for this particular distribution.

Methods
-------
rvs(mu, loc=0, size=1, random_state=None)
    Random variates.
pmf(k, mu, loc=0)
    Probability mass function.
logpmf(k, mu, loc=0)
    Log of the probability mass function.
cdf(k, mu, loc=0)
    Cumulative distribution function.
logcdf(k, mu, loc=0)
    Log of the cumulative distribution function.
sf(k, mu, loc=0)
    Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
logsf(k, mu, loc=0)
    Log of the survival function.
pp